export const LABELS = {
  home: 'Home',
  companyb: 'Company B',
  mainFolder: 'WhatsApp Database',
  whastappDatabase: 'Database 1',
  childFolder2: 'WhatsApp Number List',
  grandChild1: 'Employee List',
  grandChild2: 'Total Member List',
  folder1: 'List 1',
  folder2: 'List 2',
  folder3: 'List 3',
  grandChild3: 'Administrative List',
  childFolder3: 'Active Contact List',
  childFolder4: 'Inactive Contact List',
  pabblySubscriptionBilling: 'Pabbly Subscription Billing',
  pabblyEmailMarketing: 'Pabbly Email Marketing',
  pabblyFormBuilder: 'Pabbly Form Builder',
  pabblyEmailVerification: 'Pabbly Email Verification',
  pabblyHook: 'Pabbly Hook',
  clientA: 'Company B',
  childFolder1Client: 'Company B WhatsApp Numbers',
  grandChild1Client: 'Contact List 1',
  grandChild2Client: 'Contact List 2',
  trash: 'Trash',
};
